Models/ErrorViewModel.cs
using System;

namespace BlogSiteDemo.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Post.cs
using System;


namespace BlogSiteDemo.Models
{
	public class Post
	{
		public int ID { get; set; }

		public string Title { get; set; } = "";
		public string Body { get; set; } = "";
		public string Image { get; set; } = "";

		public string Description { get; set; } = "";
		public string Tag { get; set; } = "";
		public string Category { get; set; } = "";

		public DateTime Created { get; set; } = DateTime.Now;
	}
}

Controllers/AuthenticationController.cs
using BlogSiteDemo.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteDemo.Controllers
{
	public class AuthenticationController : Controller
	{
		private SignInManager<IdentityUser> _signInManager;
		public AuthenticationController(SignInManager<IdentityUser> signInManager)
		{
			_signInManager = signInManager;
		}

		[HttpGet]
		public IActionResult LogIn()
		{
			return View(new LogInViewModel());
		}

		[HttpPost]
		public async Task<IActionResult> LogIn(LogInViewModel logInVM)
		{
			var result = await _signInManager.PasswordSignInAsync(logInVM.UserName, logInVM.Password, false, false);
			return RedirectToAction("Index","Panel");
		}

		[HttpGet]
		public async Task<IActionResult> LogOut()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
	}
}

Controllers/HomeController.cs
using BlogSiteDemo.Data;
using BlogSiteDemo.Data.FileManager;
using BlogSiteDemo.Data.Repository;
using BlogSiteDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlogSiteDemo.Controllers
{
	public class HomeController : Controller
	{
		private IRepository _repo;
		private IFileManager _fileManager;

		public HomeController(IRepository repo,IFileManager fileManager)
		{
			_repo = repo;
			_fileManager = fileManager;
		}

		//private readonly ILogger<HomeController> _logger;

		//public HomeController(ILogger<HomeController> logger)
		//{
		//	_logger = logger;
		//}

		public IActionResult Index(string category)
		{
			var posts =string.IsNullOrEmpty(category)?_repo.GetAllPost():_repo.GetAllPost(category);
			return View(posts);
		}

		public IActionResult Post(int id)
		{
			var post = _repo.GetPost(id);
			return View(post);
		}

		[HttpGet("/Image/{image}")]
		public IActionResult Image(string image)
		{
			var mime= image.Substring(image.LastIndexOf('.')+1);
			return new FileStreamResult(_fileManager.Imagestream(image),$"image/{mime}");
		}

		//public IActionResult Privacy()
		//{
		//	return View();
		//}

		//[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		//public IActionResult Error()
		//{
		//	return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		//}
	}
}

Controllers/PanelController.cs
using BlogSiteDemo.Data.FileManager;
using BlogSiteDemo.Data.Repository;
using BlogSiteDemo.Models;
using BlogSiteDemo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BlogSiteDemo.Controllers
{
	[Authorize(Roles ="Admin")]
	public class PanelController : Controller
	{
		private IRepository _repo;
		private IFileManager _fileManager;
		public PanelController(IRepository repo, IFileManager fileManager)
		{
			_repo = repo;
			_fileManager = fileManager;
		}
		public IActionResult Index()
		{
			var posts = _repo.GetAllPost();
			return View(posts);
		}

		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id == null)
				return View(new PostViewModel());
			else
			{
				var post = _repo.GetPost((int)id);
				return View(new PostViewModel {
				ID = post.ID,
				Title = post.Title,
				Body = post.Body,
				CurrentImage = post.Image,
				Description = post.Description,
				Tag = post.Tag,
				Category = post.Category
				});
			}
		}
		[HttpPost]
		public async Task<IActionResult> Edit(PostViewModel pvm)
		{
			var post = new Post
			{
				ID = pvm.ID,
				Title = pvm.Title,
				Body = pvm.Body,
				Description = pvm.Description,
				Tag = pvm.Tag,
				Category = pvm.Category

			};
			if(pvm.Image==null)
			{
				post.Image = pvm.CurrentImage;
			}
			else
			{
				if (!string.IsNullOrEmpty(pvm.CurrentImage))
					_fileManager.RemoveImage(pvm.CurrentImage);
				post.Image = await _fileManager.SaveImage(pvm.Image);
			}
			if (post.ID > 0)
			{
				_repo.UpdatePost(post);
			}
			else
				_repo.AddPost(post);
			if (await _repo.SaveChangesAsync())
				return RedirectToAction("Index");
			else
				return View(post);
		}
		[HttpGet]
		public async Task<IActionResult> Remove(int id)
		{
			_repo.RemovePost(id);
			await _repo.SaveChangesAsync();
			return RedirectToAction("Index");


		}
	}
}

Views/Authentication/LogIn.cshtml
@model LogInViewModel
@{

}
<div>
    <form asp-controller="Authentication" asp-action="LogIn" method="post">
        <div>
            <label>User Name : </label>
            <input asp-for="UserName" />
        </div>
        <div>
            <label>Password : </label>
            <input asp-for="Password" />
        </div>
        <input type="submit" value="Log In" />
    </form>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Post>
@{
    ViewBag.Title = "";
    ViewBag.Description = "";
    ViewBag.Keywords = "";
}


<div class="main-img">
    <span class="title"> Sabrina's Blog Site! </span>
</div>
<div class="container">
    @*<ul>
            @foreach (var post in Model)
            {
                <li>
                    <a asp-controller="Home" asp-action="Post" asp-route-id="@post.ID">
                        @post.Title
                    </a>
                </li>
            }
        </ul>*@
    @foreach (var post in Model)
    {
        var img_path = $"/Image/{post.Image}";
    <a class="post" asp-controller="Home" asp-action="Post" asp-route-id="@post.ID">
        <span class="title">@post.Title</span>       
        <img src=@img_path />
    </a>
    }
</div>

Views/Home/Post.cshtml
@model Post

    @{
        ViewBag.Title = Model.Title;
        ViewBag.Description = Model.Description;
        ViewBag.Keywords = $"{Model.Tag?.Replace("," , "")}{Model.Category}";
    }
@*<div class="text-center">
    <h1 class="display-4">@Html.DisplayNameFor(model => model.Title)</h1>
    <p>@Html.DisplayNameFor(model => model.ID)</p>
    <p>@Html.DisplayNameFor(model => model.Body)</p>
</div>*@
@*<div class="text-center">
    <h1 class="display-4"> @Model.Title</h1>
    @if(!string.IsNullOrEmpty(Model.Image))
    {
        var img_path = $"/Image/{Model.Image}"
        <img src=@img_path width="500px"/>
    }
    <p>@Model.Body</p>
</div>*@
<div class="container">
    <div class="post">
        @if (!string.IsNullOrEmpty(Model.Image))
        {
            var img_path = $"/Image/{Model.Image}";
    <img src=@img_path width="500px" />
    <span class="title">@Model.Title</span>
}
    </div>
    <div class="post-body">
        @Html.Raw(Model.Body)
    </div>
</div>

Views/Panel/Edit.cshtml
@model PostViewModel
@{
      
}
<link href="~/lib/Trumbowyg-master/Trumbowyg-master/dist/ui/trumbowyg.min.css" rel="stylesheet" />
<div>
    <form asp-controller="Panel" asp-action="Edit" method="post" enctype="multipart/form-data">
        <input asp-for="ID" type="hidden" />
        <div>
            <label>Title</label>
            <input asp-for="Title" />
        </div>
        <div>
            <label>Description</label>
            <input asp-for="Description" />
        </div>
        <div>
            <label>Tag</label>
            <input asp-for="Tag" />
        </div>
        <div>
            <label>Category</label>
            <select asp-for="Category" > 
                <option value="Travel">Travel</option>
                <option value="Programming">Programming</option>
                <option value="Photography">Photography</option>
            </select>
        </div>
        <div>
            <label>Body</label>
            <textarea id="editor" asp-for="Body"></textarea>
        </div>
        <div>
            <label>Image</label>
            <input asp-for="CurrentImage" type="hidden" />
            <input asp-for="Image" />
        </div>
        <input type="submit" value="Submit" />
    </form>
</div>

@section scripts{ 
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="~/lib/Trumbowyg-master/Trumbowyg-master/dist/trumbowyg.min.js"></script>
<script>
    $('#editor').trumbowyg();
</script>
}

Views/Panel/Index.cshtml
@model IEnumerable<Post>
@{
    ViewData["Title"] = "Admin Panel Page";
}

<div>
    <h2>Admin Panel</h2>
    <a asp-controller="Panel" asp-action="Edit" >
     Add New Post
    </a>
    <div>
        <ul>
            @foreach (var post in Model)
            {
                <li>
                    @post.Title
                    -
                    <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.ID">
                        Edit
                    </a>
                    -
                    <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.ID">
                        Remove
                    </a>
                </li>
            }
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <div>
        <nav>
            <a asp-controller="Home" asp-action="Index">Sabrina's Blog</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="Travel">Travel</a>
            @*<a asp-controller="Home" asp-action="Edit">Create Post</a>*@
            <a asp-controller="Panel" asp-action="Index">Admin Panel</a>
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Authentication" asp-action="LogOut">Log Out</a>


            }
            else
            {
                <a asp-controller="Authentication" asp-action="LogIn">Log In</a>
            }

        </nav>
    </div>
    <div>
        @RenderBody()
    </div>
  @RenderSection("scripts", required: false)
</body>
</html>